# -*- coding: utf-8 -*-
"""PRODIGY_DS_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNoNYd_W9K6gy4I2t0XPx3Db0p4nrvpA
"""

import pandas as pd
import re
from textblob import TextBlob
import matplotlib.pyplot as plt
import seaborn as sns

train_data = pd.read_csv('twitter_training.csv')
validation_data = pd.read_csv('twitter_validation.csv')

data = pd.concat([train_data, validation_data])

# Inspect the data
print(data.head())

# Define a function to clean the text
def clean_text(text):
    text = re.sub(r'http\S+', '', text)  # Remove URLs
    text = re.sub(r'@\w+', '', text)     # Remove mentions
    text = re.sub(r'#\w+', '', text)     # Remove hashtags
    text = re.sub(r'\s+', ' ', text)     # Remove extra whitespace
    return text.strip()

# Display the column names of the dataframe
print(data.columns)

def get_sentiment(text):
    blob = TextBlob(text)
    sentiment = blob.sentiment.polarity
    if sentiment > 0:
        return 'positive'
    elif sentiment < 0:
        return 'negative'
    else:
        return 'neutral'

# Check the data types of each column
print(data.dtypes)

# Rename columns for easier access
data.columns = ['id1', 'topic', 'label', 'short_text', 'id2', 'platform', 'label2', 'long_text']

# Ensure all values are strings to avoid TypeError
data['sentiment'] = data['long_text'].astype(str).apply(get_sentiment)

plt.figure(figsize=(8, 5))
sns.countplot(x='sentiment', data=data, palette='viridis')
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Frequency')
plt.show()

